# Generated by Django 5.2.15 on 2026-06-08 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_mois', models.PositiveIntegerField()),
                ('periodicite', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel')], default='mensuel', max_length=15)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('objet_credit', models.TextField()),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='credits/pieces/')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_analyse', 'En analyse'), ('approuvee', 'Approuvee'), ('decaissee', 'Decaissee'), ('rejetee', 'Rejetee')], default='soumise', max_length=15)),
                ('score_eligibilite', models.IntegerField(blank=True, null=True)),
                ('commentaire_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_traites', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('date_echeance', models.DateField()),
                ('montant_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_interet', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_penalite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payee'), ('en_retard', 'En retard')], default='en_attente', max_length=12)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='credits.demandecredit')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
