# Generated by Django 5.2.15 on 2026-06-08 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_assurance', models.CharField(choices=[('vie', 'Assurance Vie'), ('deces_invalidite', 'Deces-Invalidite')], max_length=20)),
                ('description', models.TextField()),
                ('prime_mensuelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capital_garanti', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_mois', models.PositiveIntegerField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expiree'), ('resiliee', 'Resiliee')], default='active', max_length=10)),
                ('numero_police', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='assurances.produitassurance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
