# Generated by Django 5.2.15 on 2026-06-08 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moyen_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('mtn_momo', 'MTN MoMo'), ('especes', 'Especes')], max_length=15)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('echeance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='credits.echeance')),
            ],
        ),
    ]
